// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ddz.proto

package ddz

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IDENTITY int32

const (
	IDENTITY_LORD    IDENTITY = 0
	IDENTITY_FARMER1 IDENTITY = 1
	IDENTITY_FARMER2 IDENTITY = 2
)

var IDENTITY_name = map[int32]string{
	0: "LORD",
	1: "FARMER1",
	2: "FARMER2",
}

var IDENTITY_value = map[string]int32{
	"LORD":    0,
	"FARMER1": 1,
	"FARMER2": 2,
}

func (x IDENTITY) String() string {
	return proto.EnumName(IDENTITY_name, int32(x))
}

func (IDENTITY) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{0}
}

type DEALCARD_TYPE int32

const (
	DEALCARD_TYPE_OPTIMIZED DEALCARD_TYPE = 0
	DEALCARD_TYPE_SMOOTH    DEALCARD_TYPE = 1
)

var DEALCARD_TYPE_name = map[int32]string{
	0: "OPTIMIZED",
	1: "SMOOTH",
}

var DEALCARD_TYPE_value = map[string]int32{
	"OPTIMIZED": 0,
	"SMOOTH":    1,
}

func (x DEALCARD_TYPE) String() string {
	return proto.EnumName(DEALCARD_TYPE_name, int32(x))
}

func (DEALCARD_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{1}
}

type BoolReply struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolReply) Reset()         { *m = BoolReply{} }
func (m *BoolReply) String() string { return proto.CompactTextString(m) }
func (*BoolReply) ProtoMessage()    {}
func (*BoolReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{0}
}

func (m *BoolReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolReply.Unmarshal(m, b)
}
func (m *BoolReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolReply.Marshal(b, m, deterministic)
}
func (m *BoolReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolReply.Merge(m, src)
}
func (m *BoolReply) XXX_Size() int {
	return xxx_messageInfo_BoolReply.Size(m)
}
func (m *BoolReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolReply.DiscardUnknown(m)
}

var xxx_messageInfo_BoolReply proto.InternalMessageInfo

func (m *BoolReply) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type TrustShipRequest struct {
	PlayerIdentity       int32    `protobuf:"varint,1,opt,name=player_identity,json=playerIdentity,proto3" json:"player_identity,omitempty"`
	PlayerHandcard       []byte   `protobuf:"bytes,2,opt,name=player_handcard,json=playerHandcard,proto3" json:"player_handcard,omitempty"`
	LastIdentity         int32    `protobuf:"varint,3,opt,name=last_identity,json=lastIdentity,proto3" json:"last_identity,omitempty"`
	LastPlaycard         []byte   `protobuf:"bytes,4,opt,name=last_playcard,json=lastPlaycard,proto3" json:"last_playcard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrustShipRequest) Reset()         { *m = TrustShipRequest{} }
func (m *TrustShipRequest) String() string { return proto.CompactTextString(m) }
func (*TrustShipRequest) ProtoMessage()    {}
func (*TrustShipRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{1}
}

func (m *TrustShipRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustShipRequest.Unmarshal(m, b)
}
func (m *TrustShipRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustShipRequest.Marshal(b, m, deterministic)
}
func (m *TrustShipRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustShipRequest.Merge(m, src)
}
func (m *TrustShipRequest) XXX_Size() int {
	return xxx_messageInfo_TrustShipRequest.Size(m)
}
func (m *TrustShipRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustShipRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrustShipRequest proto.InternalMessageInfo

func (m *TrustShipRequest) GetPlayerIdentity() int32 {
	if m != nil {
		return m.PlayerIdentity
	}
	return 0
}

func (m *TrustShipRequest) GetPlayerHandcard() []byte {
	if m != nil {
		return m.PlayerHandcard
	}
	return nil
}

func (m *TrustShipRequest) GetLastIdentity() int32 {
	if m != nil {
		return m.LastIdentity
	}
	return 0
}

func (m *TrustShipRequest) GetLastPlaycard() []byte {
	if m != nil {
		return m.LastPlaycard
	}
	return nil
}

type RobotRequest struct {
	Playeridentity       int32    `protobuf:"varint,1,opt,name=playeridentity,proto3" json:"playeridentity,omitempty"`
	LordHandcard         []byte   `protobuf:"bytes,2,opt,name=lord_handcard,json=lordHandcard,proto3" json:"lord_handcard,omitempty"`
	Farmer1Handcard      []byte   `protobuf:"bytes,3,opt,name=farmer1_handcard,json=farmer1Handcard,proto3" json:"farmer1_handcard,omitempty"`
	Farmer2Handcard      []byte   `protobuf:"bytes,4,opt,name=farmer2_handcard,json=farmer2Handcard,proto3" json:"farmer2_handcard,omitempty"`
	LastIdentity         int32    `protobuf:"varint,5,opt,name=last_identity,json=lastIdentity,proto3" json:"last_identity,omitempty"`
	LastPlaycard         []byte   `protobuf:"bytes,6,opt,name=last_playcard,json=lastPlaycard,proto3" json:"last_playcard,omitempty"`
	LastCardstyle        int32    `protobuf:"varint,7,opt,name=last_cardstyle,json=lastCardstyle,proto3" json:"last_cardstyle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RobotRequest) Reset()         { *m = RobotRequest{} }
func (m *RobotRequest) String() string { return proto.CompactTextString(m) }
func (*RobotRequest) ProtoMessage()    {}
func (*RobotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{2}
}

func (m *RobotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RobotRequest.Unmarshal(m, b)
}
func (m *RobotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RobotRequest.Marshal(b, m, deterministic)
}
func (m *RobotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobotRequest.Merge(m, src)
}
func (m *RobotRequest) XXX_Size() int {
	return xxx_messageInfo_RobotRequest.Size(m)
}
func (m *RobotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RobotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RobotRequest proto.InternalMessageInfo

func (m *RobotRequest) GetPlayeridentity() int32 {
	if m != nil {
		return m.Playeridentity
	}
	return 0
}

func (m *RobotRequest) GetLordHandcard() []byte {
	if m != nil {
		return m.LordHandcard
	}
	return nil
}

func (m *RobotRequest) GetFarmer1Handcard() []byte {
	if m != nil {
		return m.Farmer1Handcard
	}
	return nil
}

func (m *RobotRequest) GetFarmer2Handcard() []byte {
	if m != nil {
		return m.Farmer2Handcard
	}
	return nil
}

func (m *RobotRequest) GetLastIdentity() int32 {
	if m != nil {
		return m.LastIdentity
	}
	return 0
}

func (m *RobotRequest) GetLastPlaycard() []byte {
	if m != nil {
		return m.LastPlaycard
	}
	return nil
}

func (m *RobotRequest) GetLastCardstyle() int32 {
	if m != nil {
		return m.LastCardstyle
	}
	return 0
}

type CardStyle struct {
	Style                int32    `protobuf:"varint,1,opt,name=style,proto3" json:"style,omitempty"`
	MinVal               int32    `protobuf:"varint,2,opt,name=min_val,json=minVal,proto3" json:"min_val,omitempty"`
	MaxVal               int32    `protobuf:"varint,3,opt,name=max_val,json=maxVal,proto3" json:"max_val,omitempty"`
	Extra                []byte   `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardStyle) Reset()         { *m = CardStyle{} }
func (m *CardStyle) String() string { return proto.CompactTextString(m) }
func (*CardStyle) ProtoMessage()    {}
func (*CardStyle) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{3}
}

func (m *CardStyle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardStyle.Unmarshal(m, b)
}
func (m *CardStyle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardStyle.Marshal(b, m, deterministic)
}
func (m *CardStyle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardStyle.Merge(m, src)
}
func (m *CardStyle) XXX_Size() int {
	return xxx_messageInfo_CardStyle.Size(m)
}
func (m *CardStyle) XXX_DiscardUnknown() {
	xxx_messageInfo_CardStyle.DiscardUnknown(m)
}

var xxx_messageInfo_CardStyle proto.InternalMessageInfo

func (m *CardStyle) GetStyle() int32 {
	if m != nil {
		return m.Style
	}
	return 0
}

func (m *CardStyle) GetMinVal() int32 {
	if m != nil {
		return m.MinVal
	}
	return 0
}

func (m *CardStyle) GetMaxVal() int32 {
	if m != nil {
		return m.MaxVal
	}
	return 0
}

func (m *CardStyle) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type PlayReply struct {
	Handcard             []byte     `protobuf:"bytes,1,opt,name=handcard,proto3" json:"handcard,omitempty"`
	Style                *CardStyle `protobuf:"bytes,2,opt,name=style,proto3" json:"style,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PlayReply) Reset()         { *m = PlayReply{} }
func (m *PlayReply) String() string { return proto.CompactTextString(m) }
func (*PlayReply) ProtoMessage()    {}
func (*PlayReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{4}
}

func (m *PlayReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayReply.Unmarshal(m, b)
}
func (m *PlayReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayReply.Marshal(b, m, deterministic)
}
func (m *PlayReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayReply.Merge(m, src)
}
func (m *PlayReply) XXX_Size() int {
	return xxx_messageInfo_PlayReply.Size(m)
}
func (m *PlayReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayReply.DiscardUnknown(m)
}

var xxx_messageInfo_PlayReply proto.InternalMessageInfo

func (m *PlayReply) GetHandcard() []byte {
	if m != nil {
		return m.Handcard
	}
	return nil
}

func (m *PlayReply) GetStyle() *CardStyle {
	if m != nil {
		return m.Style
	}
	return nil
}

type GameTableElement struct {
	Playeridentity       int32    `protobuf:"varint,1,opt,name=playeridentity,proto3" json:"playeridentity,omitempty"`
	LordHandcard         []byte   `protobuf:"bytes,2,opt,name=lord_handcard,json=lordHandcard,proto3" json:"lord_handcard,omitempty"`
	Farmer1Handcard      []byte   `protobuf:"bytes,3,opt,name=farmer1_handcard,json=farmer1Handcard,proto3" json:"farmer1_handcard,omitempty"`
	Farmer2Handcard      []byte   `protobuf:"bytes,4,opt,name=farmer2_handcard,json=farmer2Handcard,proto3" json:"farmer2_handcard,omitempty"`
	LastIdentity         int32    `protobuf:"varint,5,opt,name=last_identity,json=lastIdentity,proto3" json:"last_identity,omitempty"`
	LastPlaycard         []byte   `protobuf:"bytes,6,opt,name=last_playcard,json=lastPlaycard,proto3" json:"last_playcard,omitempty"`
	Result               []byte   `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameTableElement) Reset()         { *m = GameTableElement{} }
func (m *GameTableElement) String() string { return proto.CompactTextString(m) }
func (*GameTableElement) ProtoMessage()    {}
func (*GameTableElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{5}
}

func (m *GameTableElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameTableElement.Unmarshal(m, b)
}
func (m *GameTableElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameTableElement.Marshal(b, m, deterministic)
}
func (m *GameTableElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameTableElement.Merge(m, src)
}
func (m *GameTableElement) XXX_Size() int {
	return xxx_messageInfo_GameTableElement.Size(m)
}
func (m *GameTableElement) XXX_DiscardUnknown() {
	xxx_messageInfo_GameTableElement.DiscardUnknown(m)
}

var xxx_messageInfo_GameTableElement proto.InternalMessageInfo

func (m *GameTableElement) GetPlayeridentity() int32 {
	if m != nil {
		return m.Playeridentity
	}
	return 0
}

func (m *GameTableElement) GetLordHandcard() []byte {
	if m != nil {
		return m.LordHandcard
	}
	return nil
}

func (m *GameTableElement) GetFarmer1Handcard() []byte {
	if m != nil {
		return m.Farmer1Handcard
	}
	return nil
}

func (m *GameTableElement) GetFarmer2Handcard() []byte {
	if m != nil {
		return m.Farmer2Handcard
	}
	return nil
}

func (m *GameTableElement) GetLastIdentity() int32 {
	if m != nil {
		return m.LastIdentity
	}
	return 0
}

func (m *GameTableElement) GetLastPlaycard() []byte {
	if m != nil {
		return m.LastPlaycard
	}
	return nil
}

func (m *GameTableElement) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type GameTableReply struct {
	Element              []*GameTableElement `protobuf:"bytes,1,rep,name=element,proto3" json:"element,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GameTableReply) Reset()         { *m = GameTableReply{} }
func (m *GameTableReply) String() string { return proto.CompactTextString(m) }
func (*GameTableReply) ProtoMessage()    {}
func (*GameTableReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{6}
}

func (m *GameTableReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameTableReply.Unmarshal(m, b)
}
func (m *GameTableReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameTableReply.Marshal(b, m, deterministic)
}
func (m *GameTableReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameTableReply.Merge(m, src)
}
func (m *GameTableReply) XXX_Size() int {
	return xxx_messageInfo_GameTableReply.Size(m)
}
func (m *GameTableReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GameTableReply.DiscardUnknown(m)
}

var xxx_messageInfo_GameTableReply proto.InternalMessageInfo

func (m *GameTableReply) GetElement() []*GameTableElement {
	if m != nil {
		return m.Element
	}
	return nil
}

type DealCardRequest struct {
	Type                 DEALCARD_TYPE `protobuf:"varint,1,opt,name=type,proto3,enum=ddz.DEALCARD_TYPE" json:"type,omitempty"`
	Params               []byte        `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DealCardRequest) Reset()         { *m = DealCardRequest{} }
func (m *DealCardRequest) String() string { return proto.CompactTextString(m) }
func (*DealCardRequest) ProtoMessage()    {}
func (*DealCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{7}
}

func (m *DealCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealCardRequest.Unmarshal(m, b)
}
func (m *DealCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealCardRequest.Marshal(b, m, deterministic)
}
func (m *DealCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealCardRequest.Merge(m, src)
}
func (m *DealCardRequest) XXX_Size() int {
	return xxx_messageInfo_DealCardRequest.Size(m)
}
func (m *DealCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DealCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DealCardRequest proto.InternalMessageInfo

func (m *DealCardRequest) GetType() DEALCARD_TYPE {
	if m != nil {
		return m.Type
	}
	return DEALCARD_TYPE_OPTIMIZED
}

func (m *DealCardRequest) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

type DealCardReply struct {
	Player0              []byte   `protobuf:"bytes,1,opt,name=player0,proto3" json:"player0,omitempty"`
	Player1              []byte   `protobuf:"bytes,2,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2              []byte   `protobuf:"bytes,3,opt,name=player2,proto3" json:"player2,omitempty"`
	Extra                []byte   `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealCardReply) Reset()         { *m = DealCardReply{} }
func (m *DealCardReply) String() string { return proto.CompactTextString(m) }
func (*DealCardReply) ProtoMessage()    {}
func (*DealCardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{8}
}

func (m *DealCardReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealCardReply.Unmarshal(m, b)
}
func (m *DealCardReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealCardReply.Marshal(b, m, deterministic)
}
func (m *DealCardReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealCardReply.Merge(m, src)
}
func (m *DealCardReply) XXX_Size() int {
	return xxx_messageInfo_DealCardReply.Size(m)
}
func (m *DealCardReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DealCardReply.DiscardUnknown(m)
}

var xxx_messageInfo_DealCardReply proto.InternalMessageInfo

func (m *DealCardReply) GetPlayer0() []byte {
	if m != nil {
		return m.Player0
	}
	return nil
}

func (m *DealCardReply) GetPlayer1() []byte {
	if m != nil {
		return m.Player1
	}
	return nil
}

func (m *DealCardReply) GetPlayer2() []byte {
	if m != nil {
		return m.Player2
	}
	return nil
}

func (m *DealCardReply) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type HandCardRequest struct {
	Cards                []byte   `protobuf:"bytes,1,opt,name=cards,proto3" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandCardRequest) Reset()         { *m = HandCardRequest{} }
func (m *HandCardRequest) String() string { return proto.CompactTextString(m) }
func (*HandCardRequest) ProtoMessage()    {}
func (*HandCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{9}
}

func (m *HandCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandCardRequest.Unmarshal(m, b)
}
func (m *HandCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandCardRequest.Marshal(b, m, deterministic)
}
func (m *HandCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandCardRequest.Merge(m, src)
}
func (m *HandCardRequest) XXX_Size() int {
	return xxx_messageInfo_HandCardRequest.Size(m)
}
func (m *HandCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandCardRequest proto.InternalMessageInfo

func (m *HandCardRequest) GetCards() []byte {
	if m != nil {
		return m.Cards
	}
	return nil
}

type HandCardAnalysisRequest struct {
	Handcards            []*HandCardRequest `protobuf:"bytes,1,rep,name=handcards,proto3" json:"handcards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *HandCardAnalysisRequest) Reset()         { *m = HandCardAnalysisRequest{} }
func (m *HandCardAnalysisRequest) String() string { return proto.CompactTextString(m) }
func (*HandCardAnalysisRequest) ProtoMessage()    {}
func (*HandCardAnalysisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{10}
}

func (m *HandCardAnalysisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandCardAnalysisRequest.Unmarshal(m, b)
}
func (m *HandCardAnalysisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandCardAnalysisRequest.Marshal(b, m, deterministic)
}
func (m *HandCardAnalysisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandCardAnalysisRequest.Merge(m, src)
}
func (m *HandCardAnalysisRequest) XXX_Size() int {
	return xxx_messageInfo_HandCardAnalysisRequest.Size(m)
}
func (m *HandCardAnalysisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandCardAnalysisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandCardAnalysisRequest proto.InternalMessageInfo

func (m *HandCardAnalysisRequest) GetHandcards() []*HandCardRequest {
	if m != nil {
		return m.Handcards
	}
	return nil
}

type HandCardAnalysisResult struct {
	Power                int32        `protobuf:"varint,1,opt,name=power,proto3" json:"power,omitempty"`
	MinStep              int32        `protobuf:"varint,2,opt,name=min_step,json=minStep,proto3" json:"min_step,omitempty"`
	MinStepWithoutBoom   int32        `protobuf:"varint,3,opt,name=min_step_without_boom,json=minStepWithoutBoom,proto3" json:"min_step_without_boom,omitempty"`
	Singles              []byte       `protobuf:"bytes,4,opt,name=singles,proto3" json:"singles,omitempty"`
	Doubles              []byte       `protobuf:"bytes,5,opt,name=doubles,proto3" json:"doubles,omitempty"`
	Triples              []byte       `protobuf:"bytes,6,opt,name=triples,proto3" json:"triples,omitempty"`
	AllStyle             []*CardStyle `protobuf:"bytes,7,rep,name=all_style,json=allStyle,proto3" json:"all_style,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HandCardAnalysisResult) Reset()         { *m = HandCardAnalysisResult{} }
func (m *HandCardAnalysisResult) String() string { return proto.CompactTextString(m) }
func (*HandCardAnalysisResult) ProtoMessage()    {}
func (*HandCardAnalysisResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{11}
}

func (m *HandCardAnalysisResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandCardAnalysisResult.Unmarshal(m, b)
}
func (m *HandCardAnalysisResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandCardAnalysisResult.Marshal(b, m, deterministic)
}
func (m *HandCardAnalysisResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandCardAnalysisResult.Merge(m, src)
}
func (m *HandCardAnalysisResult) XXX_Size() int {
	return xxx_messageInfo_HandCardAnalysisResult.Size(m)
}
func (m *HandCardAnalysisResult) XXX_DiscardUnknown() {
	xxx_messageInfo_HandCardAnalysisResult.DiscardUnknown(m)
}

var xxx_messageInfo_HandCardAnalysisResult proto.InternalMessageInfo

func (m *HandCardAnalysisResult) GetPower() int32 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *HandCardAnalysisResult) GetMinStep() int32 {
	if m != nil {
		return m.MinStep
	}
	return 0
}

func (m *HandCardAnalysisResult) GetMinStepWithoutBoom() int32 {
	if m != nil {
		return m.MinStepWithoutBoom
	}
	return 0
}

func (m *HandCardAnalysisResult) GetSingles() []byte {
	if m != nil {
		return m.Singles
	}
	return nil
}

func (m *HandCardAnalysisResult) GetDoubles() []byte {
	if m != nil {
		return m.Doubles
	}
	return nil
}

func (m *HandCardAnalysisResult) GetTriples() []byte {
	if m != nil {
		return m.Triples
	}
	return nil
}

func (m *HandCardAnalysisResult) GetAllStyle() []*CardStyle {
	if m != nil {
		return m.AllStyle
	}
	return nil
}

type HandCardAnalysisReply struct {
	Results              []*HandCardAnalysisResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *HandCardAnalysisReply) Reset()         { *m = HandCardAnalysisReply{} }
func (m *HandCardAnalysisReply) String() string { return proto.CompactTextString(m) }
func (*HandCardAnalysisReply) ProtoMessage()    {}
func (*HandCardAnalysisReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{12}
}

func (m *HandCardAnalysisReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandCardAnalysisReply.Unmarshal(m, b)
}
func (m *HandCardAnalysisReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandCardAnalysisReply.Marshal(b, m, deterministic)
}
func (m *HandCardAnalysisReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandCardAnalysisReply.Merge(m, src)
}
func (m *HandCardAnalysisReply) XXX_Size() int {
	return xxx_messageInfo_HandCardAnalysisReply.Size(m)
}
func (m *HandCardAnalysisReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HandCardAnalysisReply.DiscardUnknown(m)
}

var xxx_messageInfo_HandCardAnalysisReply proto.InternalMessageInfo

func (m *HandCardAnalysisReply) GetResults() []*HandCardAnalysisResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterEnum("ddz.IDENTITY", IDENTITY_name, IDENTITY_value)
	proto.RegisterEnum("ddz.DEALCARD_TYPE", DEALCARD_TYPE_name, DEALCARD_TYPE_value)
	proto.RegisterType((*BoolReply)(nil), "ddz.BoolReply")
	proto.RegisterType((*TrustShipRequest)(nil), "ddz.TrustShipRequest")
	proto.RegisterType((*RobotRequest)(nil), "ddz.RobotRequest")
	proto.RegisterType((*CardStyle)(nil), "ddz.CardStyle")
	proto.RegisterType((*PlayReply)(nil), "ddz.PlayReply")
	proto.RegisterType((*GameTableElement)(nil), "ddz.GameTableElement")
	proto.RegisterType((*GameTableReply)(nil), "ddz.GameTableReply")
	proto.RegisterType((*DealCardRequest)(nil), "ddz.DealCardRequest")
	proto.RegisterType((*DealCardReply)(nil), "ddz.DealCardReply")
	proto.RegisterType((*HandCardRequest)(nil), "ddz.HandCardRequest")
	proto.RegisterType((*HandCardAnalysisRequest)(nil), "ddz.HandCardAnalysisRequest")
	proto.RegisterType((*HandCardAnalysisResult)(nil), "ddz.HandCardAnalysisResult")
	proto.RegisterType((*HandCardAnalysisReply)(nil), "ddz.HandCardAnalysisReply")
}

func init() { proto.RegisterFile("ddz.proto", fileDescriptor_329728c9c8fc6b4b) }

var fileDescriptor_329728c9c8fc6b4b = []byte{
	// 834 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x56, 0xcb, 0x52, 0xe3, 0x46,
	0x14, 0x45, 0x7e, 0xfb, 0xe2, 0x57, 0x3a, 0x06, 0x1c, 0x27, 0x0b, 0x4a, 0x24, 0x81, 0x40, 0x15,
	0x60, 0xa5, 0xf2, 0x01, 0x06, 0x3b, 0xe0, 0x14, 0xc6, 0x44, 0x76, 0x25, 0xc5, 0x6c, 0x5c, 0x6d,
	0xd4, 0x33, 0x56, 0x55, 0xcb, 0xd2, 0x48, 0x6d, 0xc0, 0xfc, 0xc0, 0x7c, 0xc2, 0xec, 0xe7, 0x03,
	0xe6, 0xf7, 0x66, 0x3b, 0xd5, 0x2f, 0xcb, 0x0f, 0x5c, 0x35, 0xfb, 0xd9, 0xf9, 0xdc, 0x73, 0xfa,
	0xea, 0xf6, 0xe9, 0x7b, 0xbb, 0x0d, 0x79, 0xc7, 0x79, 0x39, 0x0d, 0x42, 0x9f, 0xf9, 0x28, 0xe9,
	0x38, 0x2f, 0xe6, 0x01, 0xe4, 0x2f, 0x7c, 0x9f, 0xda, 0x24, 0xa0, 0x33, 0xb4, 0x0b, 0x99, 0x90,
	0x44, 0x53, 0xca, 0x6a, 0xc6, 0xbe, 0x71, 0x94, 0xb3, 0x15, 0x32, 0x3f, 0x1b, 0x50, 0x19, 0x84,
	0xd3, 0x88, 0xf5, 0xc7, 0x6e, 0x60, 0x93, 0xf7, 0x53, 0x12, 0x31, 0x74, 0x08, 0xe5, 0x80, 0xe2,
	0x19, 0x09, 0x87, 0xae, 0x43, 0x26, 0xcc, 0x65, 0x33, 0xb1, 0x2a, 0x6d, 0x97, 0x64, 0xb8, 0xa3,
	0xa2, 0x0b, 0xc2, 0x31, 0x9e, 0x38, 0x0f, 0x38, 0x74, 0x6a, 0x89, 0x7d, 0xe3, 0xa8, 0xa0, 0x85,
	0xd7, 0x2a, 0x8a, 0x0e, 0xa0, 0x48, 0x71, 0xc4, 0xe2, 0x7c, 0x49, 0x91, 0xaf, 0xc0, 0x83, 0xf3,
	0x6c, 0x5a, 0xc4, 0xd7, 0x8a, 0x5c, 0x29, 0x91, 0x4b, 0x88, 0xee, 0x54, 0xcc, 0xfc, 0x94, 0x80,
	0x82, 0xed, 0x8f, 0x7c, 0xa6, 0x8b, 0xfd, 0x1d, 0xd4, 0xc7, 0x5e, 0xaf, 0xd5, 0x5d, 0xcc, 0xee,
	0x87, 0xce, 0x6a, 0xa5, 0x05, 0x1e, 0x9c, 0xd7, 0xf9, 0x07, 0x54, 0xde, 0xe2, 0xd0, 0x23, 0x61,
	0x23, 0xd6, 0x25, 0x85, 0xae, 0xac, 0xe2, 0xeb, 0x52, 0x2b, 0x96, 0xa6, 0x16, 0xa5, 0xd6, 0xe6,
	0xdd, 0xa7, 0xbf, 0x65, 0xf7, 0x99, 0xf5, 0xdd, 0xa3, 0xdf, 0xa0, 0x24, 0x44, 0x1c, 0x44, 0x6c,
	0x46, 0x49, 0x2d, 0x2b, 0x52, 0x89, 0xa5, 0x97, 0x3a, 0x68, 0xba, 0x90, 0xe7, 0xa0, 0xcf, 0x01,
	0xaa, 0x42, 0x5a, 0x4a, 0xa5, 0x2f, 0x12, 0xa0, 0x3d, 0xc8, 0x7a, 0xee, 0x64, 0xf8, 0x88, 0xa9,
	0x30, 0x22, 0x6d, 0x67, 0x3c, 0x77, 0xf2, 0x1f, 0xa6, 0x82, 0xc0, 0xcf, 0x82, 0x48, 0x2a, 0x02,
	0x3f, 0x73, 0xa2, 0x0a, 0x69, 0xf2, 0xcc, 0x42, 0xac, 0x76, 0x29, 0x81, 0xd9, 0x85, 0x3c, 0xaf,
	0x4e, 0x76, 0x59, 0x1d, 0x72, 0x73, 0x2f, 0x0c, 0xa1, 0x9a, 0x63, 0xf4, 0xab, 0x2e, 0x83, 0x7f,
	0x6e, 0xdb, 0x2a, 0x9d, 0xf2, 0x76, 0x9d, 0x57, 0xa9, 0xca, 0x32, 0x3f, 0x26, 0xa0, 0x72, 0x85,
	0x3d, 0x32, 0xc0, 0x23, 0x4a, 0xda, 0x94, 0x78, 0x64, 0xf2, 0x9d, 0x1d, 0x71, 0x3c, 0xa9, 0x59,
	0xc1, 0xea, 0x49, 0x6d, 0x42, 0x69, 0x6e, 0x8c, 0x74, 0xfb, 0x0c, 0xb2, 0x44, 0x3a, 0x54, 0x33,
	0xf6, 0x93, 0x47, 0xdb, 0xd6, 0x8e, 0xf0, 0x74, 0xd5, 0x3e, 0x5b, 0xab, 0xcc, 0x7f, 0xa1, 0xdc,
	0x22, 0x98, 0x72, 0xd3, 0xe3, 0xe9, 0x49, 0xb1, 0x59, 0x20, 0x7b, 0xa3, 0x64, 0x21, 0x91, 0xa0,
	0xd5, 0x6e, 0xde, 0x5c, 0x36, 0xed, 0xd6, 0x70, 0x70, 0x7f, 0xd7, 0xb6, 0x05, 0xcf, 0xab, 0x0a,
	0x70, 0x88, 0xbd, 0x48, 0x79, 0xaa, 0x90, 0x19, 0x41, 0x31, 0x4e, 0xc9, 0x8b, 0xaa, 0x41, 0x56,
	0x9e, 0xca, 0xb9, 0xea, 0x00, 0x0d, 0x63, 0xa6, 0xa1, 0x72, 0x68, 0x18, 0x33, 0x96, 0x3a, 0x09,
	0x0d, 0x37, 0xf4, 0xdc, 0x21, 0x94, 0xb9, 0xf1, 0x8b, 0xfb, 0xa8, 0x42, 0x5a, 0xcc, 0x84, 0xfa,
	0xa8, 0x04, 0x66, 0x17, 0xf6, 0xb4, 0xb0, 0x39, 0xc1, 0x74, 0x16, 0xb9, 0x91, 0x5e, 0x60, 0x41,
	0x5e, 0x9f, 0x69, 0xa4, 0xec, 0xab, 0x8a, 0xdd, 0xaf, 0x64, 0xb6, 0x63, 0x99, 0xf9, 0xc5, 0x80,
	0xdd, 0xf5, 0x7c, 0xfc, 0x74, 0xf8, 0xf7, 0x03, 0xff, 0x89, 0x84, 0x7a, 0xc8, 0x04, 0x40, 0x3f,
	0x41, 0x8e, 0x0f, 0x59, 0xc4, 0x48, 0xa0, 0xa6, 0x8c, 0x0f, 0x5d, 0x9f, 0x91, 0x00, 0x35, 0x60,
	0x47, 0x53, 0xc3, 0x27, 0x97, 0x8d, 0xfd, 0x29, 0x1b, 0x8e, 0x7c, 0xdf, 0x53, 0x43, 0x87, 0x94,
	0xee, 0x7f, 0x49, 0x5d, 0xf8, 0xbe, 0xc7, 0x6d, 0x8a, 0xdc, 0xc9, 0x3b, 0x4a, 0x22, 0x65, 0x87,
	0x86, 0x9c, 0x71, 0xfc, 0xe9, 0x88, 0x33, 0x69, 0xc9, 0x28, 0xc8, 0x19, 0x16, 0xba, 0x01, 0x67,
	0x64, 0xb3, 0x69, 0x88, 0x4e, 0x20, 0x8f, 0x29, 0x1d, 0xea, 0x5b, 0x24, 0xf9, 0xca, 0x4c, 0xe6,
	0x30, 0xa5, 0xe2, 0x97, 0x79, 0x0b, 0x3b, 0xeb, 0x1b, 0xe7, 0xc7, 0xfd, 0x17, 0x64, 0x65, 0x7f,
	0x6a, 0x13, 0x7f, 0x5e, 0x32, 0x71, 0xd9, 0x25, 0x5b, 0x6b, 0x8f, 0x4f, 0x21, 0xd7, 0x69, 0xb5,
	0x6f, 0x07, 0x9d, 0xc1, 0x3d, 0xca, 0x41, 0xea, 0xa6, 0x67, 0xb7, 0x2a, 0x5b, 0x68, 0x1b, 0xb2,
	0x7f, 0x37, 0xed, 0x6e, 0xdb, 0x6e, 0x54, 0x8c, 0x18, 0x58, 0x95, 0xc4, 0xf1, 0x31, 0x14, 0x97,
	0xba, 0x12, 0x15, 0x21, 0xdf, 0xbb, 0x1b, 0x74, 0xba, 0x9d, 0x37, 0x6d, 0xbe, 0x12, 0x20, 0xd3,
	0xef, 0xf6, 0x7a, 0x83, 0xeb, 0x8a, 0x61, 0x5d, 0xc7, 0x5d, 0xde, 0x27, 0xe1, 0xa3, 0xfb, 0x40,
	0x78, 0x95, 0x57, 0x44, 0xdc, 0x8f, 0x48, 0x1e, 0xf2, 0xca, 0x18, 0xd4, 0xd1, 0x4a, 0x34, 0xa0,
	0x33, 0x73, 0xcb, 0xba, 0x54, 0x6f, 0x63, 0x34, 0x76, 0x03, 0x9d, 0xea, 0x0c, 0x52, 0xfc, 0xa9,
	0x44, 0x72, 0xd6, 0x56, 0x9f, 0xce, 0xba, 0xb4, 0x70, 0x7e, 0x23, 0x9a, 0x5b, 0xd6, 0x07, 0x43,
	0x3d, 0x58, 0x3a, 0xc3, 0x09, 0xa4, 0x38, 0x8f, 0x7e, 0x10, 0xd2, 0xc5, 0xb7, 0x6c, 0x7d, 0x35,
	0xfa, 0x07, 0x0a, 0x8b, 0x3e, 0xa2, 0x5f, 0x36, 0xd8, 0x2b, 0xd7, 0xd7, 0x37, 0xb0, 0xb2, 0x92,
	0xd6, 0xc2, 0xd5, 0xaa, 0x8b, 0x39, 0xdf, 0x5c, 0xcc, 0x8f, 0xcb, 0xb7, 0x89, 0xca, 0x32, 0xca,
	0x88, 0xbf, 0x18, 0x7f, 0x7e, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x0f, 0x73, 0xee, 0x6f, 0x08,
	0x00, 0x00,
}
