// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ddz.proto

package ddz

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IDENTITY int32

const (
	IDENTITY_LORD    IDENTITY = 0
	IDENTITY_FARMER1 IDENTITY = 1
	IDENTITY_FARMER2 IDENTITY = 2
)

var IDENTITY_name = map[int32]string{
	0: "LORD",
	1: "FARMER1",
	2: "FARMER2",
}

var IDENTITY_value = map[string]int32{
	"LORD":    0,
	"FARMER1": 1,
	"FARMER2": 2,
}

func (x IDENTITY) String() string {
	return proto.EnumName(IDENTITY_name, int32(x))
}

func (IDENTITY) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{0}
}

type DEALCARD_TYPE int32

const (
	DEALCARD_TYPE_OPTIMIZED DEALCARD_TYPE = 0
	DEALCARD_TYPE_SMOOTH    DEALCARD_TYPE = 1
)

var DEALCARD_TYPE_name = map[int32]string{
	0: "OPTIMIZED",
	1: "SMOOTH",
}

var DEALCARD_TYPE_value = map[string]int32{
	"OPTIMIZED": 0,
	"SMOOTH":    1,
}

func (x DEALCARD_TYPE) String() string {
	return proto.EnumName(DEALCARD_TYPE_name, int32(x))
}

func (DEALCARD_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{1}
}

type BoolReply struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolReply) Reset()         { *m = BoolReply{} }
func (m *BoolReply) String() string { return proto.CompactTextString(m) }
func (*BoolReply) ProtoMessage()    {}
func (*BoolReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{0}
}

func (m *BoolReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolReply.Unmarshal(m, b)
}
func (m *BoolReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolReply.Marshal(b, m, deterministic)
}
func (m *BoolReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolReply.Merge(m, src)
}
func (m *BoolReply) XXX_Size() int {
	return xxx_messageInfo_BoolReply.Size(m)
}
func (m *BoolReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolReply.DiscardUnknown(m)
}

var xxx_messageInfo_BoolReply proto.InternalMessageInfo

func (m *BoolReply) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type TrustShipRequest struct {
	PlayerIdentity       int32    `protobuf:"varint,1,opt,name=player_identity,json=playerIdentity,proto3" json:"player_identity,omitempty"`
	PlayerHandcard       []byte   `protobuf:"bytes,2,opt,name=player_handcard,json=playerHandcard,proto3" json:"player_handcard,omitempty"`
	LastIdentity         int32    `protobuf:"varint,3,opt,name=last_identity,json=lastIdentity,proto3" json:"last_identity,omitempty"`
	LastPlaycard         []byte   `protobuf:"bytes,4,opt,name=last_playcard,json=lastPlaycard,proto3" json:"last_playcard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrustShipRequest) Reset()         { *m = TrustShipRequest{} }
func (m *TrustShipRequest) String() string { return proto.CompactTextString(m) }
func (*TrustShipRequest) ProtoMessage()    {}
func (*TrustShipRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{1}
}

func (m *TrustShipRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrustShipRequest.Unmarshal(m, b)
}
func (m *TrustShipRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrustShipRequest.Marshal(b, m, deterministic)
}
func (m *TrustShipRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrustShipRequest.Merge(m, src)
}
func (m *TrustShipRequest) XXX_Size() int {
	return xxx_messageInfo_TrustShipRequest.Size(m)
}
func (m *TrustShipRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrustShipRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrustShipRequest proto.InternalMessageInfo

func (m *TrustShipRequest) GetPlayerIdentity() int32 {
	if m != nil {
		return m.PlayerIdentity
	}
	return 0
}

func (m *TrustShipRequest) GetPlayerHandcard() []byte {
	if m != nil {
		return m.PlayerHandcard
	}
	return nil
}

func (m *TrustShipRequest) GetLastIdentity() int32 {
	if m != nil {
		return m.LastIdentity
	}
	return 0
}

func (m *TrustShipRequest) GetLastPlaycard() []byte {
	if m != nil {
		return m.LastPlaycard
	}
	return nil
}

type RobotRequest struct {
	Playeridentity       int32    `protobuf:"varint,1,opt,name=playeridentity,proto3" json:"playeridentity,omitempty"`
	LordHandcard         []byte   `protobuf:"bytes,2,opt,name=lord_handcard,json=lordHandcard,proto3" json:"lord_handcard,omitempty"`
	Farmer1Handcard      []byte   `protobuf:"bytes,3,opt,name=farmer1_handcard,json=farmer1Handcard,proto3" json:"farmer1_handcard,omitempty"`
	Farmer2Handcard      []byte   `protobuf:"bytes,4,opt,name=farmer2_handcard,json=farmer2Handcard,proto3" json:"farmer2_handcard,omitempty"`
	LastIdentity         int32    `protobuf:"varint,5,opt,name=last_identity,json=lastIdentity,proto3" json:"last_identity,omitempty"`
	LastPlaycard         []byte   `protobuf:"bytes,6,opt,name=last_playcard,json=lastPlaycard,proto3" json:"last_playcard,omitempty"`
	LastCardstyle        int32    `protobuf:"varint,7,opt,name=last_cardstyle,json=lastCardstyle,proto3" json:"last_cardstyle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RobotRequest) Reset()         { *m = RobotRequest{} }
func (m *RobotRequest) String() string { return proto.CompactTextString(m) }
func (*RobotRequest) ProtoMessage()    {}
func (*RobotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{2}
}

func (m *RobotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RobotRequest.Unmarshal(m, b)
}
func (m *RobotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RobotRequest.Marshal(b, m, deterministic)
}
func (m *RobotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobotRequest.Merge(m, src)
}
func (m *RobotRequest) XXX_Size() int {
	return xxx_messageInfo_RobotRequest.Size(m)
}
func (m *RobotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RobotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RobotRequest proto.InternalMessageInfo

func (m *RobotRequest) GetPlayeridentity() int32 {
	if m != nil {
		return m.Playeridentity
	}
	return 0
}

func (m *RobotRequest) GetLordHandcard() []byte {
	if m != nil {
		return m.LordHandcard
	}
	return nil
}

func (m *RobotRequest) GetFarmer1Handcard() []byte {
	if m != nil {
		return m.Farmer1Handcard
	}
	return nil
}

func (m *RobotRequest) GetFarmer2Handcard() []byte {
	if m != nil {
		return m.Farmer2Handcard
	}
	return nil
}

func (m *RobotRequest) GetLastIdentity() int32 {
	if m != nil {
		return m.LastIdentity
	}
	return 0
}

func (m *RobotRequest) GetLastPlaycard() []byte {
	if m != nil {
		return m.LastPlaycard
	}
	return nil
}

func (m *RobotRequest) GetLastCardstyle() int32 {
	if m != nil {
		return m.LastCardstyle
	}
	return 0
}

type CardStyle struct {
	Style                int32    `protobuf:"varint,1,opt,name=style,proto3" json:"style,omitempty"`
	MinVal               int32    `protobuf:"varint,2,opt,name=min_val,json=minVal,proto3" json:"min_val,omitempty"`
	MaxVal               int32    `protobuf:"varint,3,opt,name=max_val,json=maxVal,proto3" json:"max_val,omitempty"`
	Extra                []byte   `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardStyle) Reset()         { *m = CardStyle{} }
func (m *CardStyle) String() string { return proto.CompactTextString(m) }
func (*CardStyle) ProtoMessage()    {}
func (*CardStyle) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{3}
}

func (m *CardStyle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardStyle.Unmarshal(m, b)
}
func (m *CardStyle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardStyle.Marshal(b, m, deterministic)
}
func (m *CardStyle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardStyle.Merge(m, src)
}
func (m *CardStyle) XXX_Size() int {
	return xxx_messageInfo_CardStyle.Size(m)
}
func (m *CardStyle) XXX_DiscardUnknown() {
	xxx_messageInfo_CardStyle.DiscardUnknown(m)
}

var xxx_messageInfo_CardStyle proto.InternalMessageInfo

func (m *CardStyle) GetStyle() int32 {
	if m != nil {
		return m.Style
	}
	return 0
}

func (m *CardStyle) GetMinVal() int32 {
	if m != nil {
		return m.MinVal
	}
	return 0
}

func (m *CardStyle) GetMaxVal() int32 {
	if m != nil {
		return m.MaxVal
	}
	return 0
}

func (m *CardStyle) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type PlayReply struct {
	Handcard             []byte     `protobuf:"bytes,1,opt,name=handcard,proto3" json:"handcard,omitempty"`
	Style                *CardStyle `protobuf:"bytes,2,opt,name=style,proto3" json:"style,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PlayReply) Reset()         { *m = PlayReply{} }
func (m *PlayReply) String() string { return proto.CompactTextString(m) }
func (*PlayReply) ProtoMessage()    {}
func (*PlayReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{4}
}

func (m *PlayReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayReply.Unmarshal(m, b)
}
func (m *PlayReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayReply.Marshal(b, m, deterministic)
}
func (m *PlayReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayReply.Merge(m, src)
}
func (m *PlayReply) XXX_Size() int {
	return xxx_messageInfo_PlayReply.Size(m)
}
func (m *PlayReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayReply.DiscardUnknown(m)
}

var xxx_messageInfo_PlayReply proto.InternalMessageInfo

func (m *PlayReply) GetHandcard() []byte {
	if m != nil {
		return m.Handcard
	}
	return nil
}

func (m *PlayReply) GetStyle() *CardStyle {
	if m != nil {
		return m.Style
	}
	return nil
}

type GameTableElement struct {
	Playeridentity       int32    `protobuf:"varint,1,opt,name=playeridentity,proto3" json:"playeridentity,omitempty"`
	LordHandcard         []byte   `protobuf:"bytes,2,opt,name=lord_handcard,json=lordHandcard,proto3" json:"lord_handcard,omitempty"`
	Farmer1Handcard      []byte   `protobuf:"bytes,3,opt,name=farmer1_handcard,json=farmer1Handcard,proto3" json:"farmer1_handcard,omitempty"`
	Farmer2Handcard      []byte   `protobuf:"bytes,4,opt,name=farmer2_handcard,json=farmer2Handcard,proto3" json:"farmer2_handcard,omitempty"`
	LastIdentity         int32    `protobuf:"varint,5,opt,name=last_identity,json=lastIdentity,proto3" json:"last_identity,omitempty"`
	LastPlaycard         []byte   `protobuf:"bytes,6,opt,name=last_playcard,json=lastPlaycard,proto3" json:"last_playcard,omitempty"`
	Result               []byte   `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameTableElement) Reset()         { *m = GameTableElement{} }
func (m *GameTableElement) String() string { return proto.CompactTextString(m) }
func (*GameTableElement) ProtoMessage()    {}
func (*GameTableElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{5}
}

func (m *GameTableElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameTableElement.Unmarshal(m, b)
}
func (m *GameTableElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameTableElement.Marshal(b, m, deterministic)
}
func (m *GameTableElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameTableElement.Merge(m, src)
}
func (m *GameTableElement) XXX_Size() int {
	return xxx_messageInfo_GameTableElement.Size(m)
}
func (m *GameTableElement) XXX_DiscardUnknown() {
	xxx_messageInfo_GameTableElement.DiscardUnknown(m)
}

var xxx_messageInfo_GameTableElement proto.InternalMessageInfo

func (m *GameTableElement) GetPlayeridentity() int32 {
	if m != nil {
		return m.Playeridentity
	}
	return 0
}

func (m *GameTableElement) GetLordHandcard() []byte {
	if m != nil {
		return m.LordHandcard
	}
	return nil
}

func (m *GameTableElement) GetFarmer1Handcard() []byte {
	if m != nil {
		return m.Farmer1Handcard
	}
	return nil
}

func (m *GameTableElement) GetFarmer2Handcard() []byte {
	if m != nil {
		return m.Farmer2Handcard
	}
	return nil
}

func (m *GameTableElement) GetLastIdentity() int32 {
	if m != nil {
		return m.LastIdentity
	}
	return 0
}

func (m *GameTableElement) GetLastPlaycard() []byte {
	if m != nil {
		return m.LastPlaycard
	}
	return nil
}

func (m *GameTableElement) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type GameTableReply struct {
	Element              []*GameTableElement `protobuf:"bytes,1,rep,name=element,proto3" json:"element,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GameTableReply) Reset()         { *m = GameTableReply{} }
func (m *GameTableReply) String() string { return proto.CompactTextString(m) }
func (*GameTableReply) ProtoMessage()    {}
func (*GameTableReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{6}
}

func (m *GameTableReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameTableReply.Unmarshal(m, b)
}
func (m *GameTableReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameTableReply.Marshal(b, m, deterministic)
}
func (m *GameTableReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameTableReply.Merge(m, src)
}
func (m *GameTableReply) XXX_Size() int {
	return xxx_messageInfo_GameTableReply.Size(m)
}
func (m *GameTableReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GameTableReply.DiscardUnknown(m)
}

var xxx_messageInfo_GameTableReply proto.InternalMessageInfo

func (m *GameTableReply) GetElement() []*GameTableElement {
	if m != nil {
		return m.Element
	}
	return nil
}

type DealCardRequest struct {
	Type                 DEALCARD_TYPE `protobuf:"varint,1,opt,name=type,proto3,enum=ddz.DEALCARD_TYPE" json:"type,omitempty"`
	Params               []byte        `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DealCardRequest) Reset()         { *m = DealCardRequest{} }
func (m *DealCardRequest) String() string { return proto.CompactTextString(m) }
func (*DealCardRequest) ProtoMessage()    {}
func (*DealCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{7}
}

func (m *DealCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealCardRequest.Unmarshal(m, b)
}
func (m *DealCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealCardRequest.Marshal(b, m, deterministic)
}
func (m *DealCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealCardRequest.Merge(m, src)
}
func (m *DealCardRequest) XXX_Size() int {
	return xxx_messageInfo_DealCardRequest.Size(m)
}
func (m *DealCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DealCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DealCardRequest proto.InternalMessageInfo

func (m *DealCardRequest) GetType() DEALCARD_TYPE {
	if m != nil {
		return m.Type
	}
	return DEALCARD_TYPE_OPTIMIZED
}

func (m *DealCardRequest) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

type DealCardReply struct {
	Player0              []byte   `protobuf:"bytes,1,opt,name=player0,proto3" json:"player0,omitempty"`
	Player1              []byte   `protobuf:"bytes,2,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2              []byte   `protobuf:"bytes,3,opt,name=player2,proto3" json:"player2,omitempty"`
	Extra                []byte   `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealCardReply) Reset()         { *m = DealCardReply{} }
func (m *DealCardReply) String() string { return proto.CompactTextString(m) }
func (*DealCardReply) ProtoMessage()    {}
func (*DealCardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_329728c9c8fc6b4b, []int{8}
}

func (m *DealCardReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealCardReply.Unmarshal(m, b)
}
func (m *DealCardReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealCardReply.Marshal(b, m, deterministic)
}
func (m *DealCardReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealCardReply.Merge(m, src)
}
func (m *DealCardReply) XXX_Size() int {
	return xxx_messageInfo_DealCardReply.Size(m)
}
func (m *DealCardReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DealCardReply.DiscardUnknown(m)
}

var xxx_messageInfo_DealCardReply proto.InternalMessageInfo

func (m *DealCardReply) GetPlayer0() []byte {
	if m != nil {
		return m.Player0
	}
	return nil
}

func (m *DealCardReply) GetPlayer1() []byte {
	if m != nil {
		return m.Player1
	}
	return nil
}

func (m *DealCardReply) GetPlayer2() []byte {
	if m != nil {
		return m.Player2
	}
	return nil
}

func (m *DealCardReply) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

func init() {
	proto.RegisterEnum("ddz.IDENTITY", IDENTITY_name, IDENTITY_value)
	proto.RegisterEnum("ddz.DEALCARD_TYPE", DEALCARD_TYPE_name, DEALCARD_TYPE_value)
	proto.RegisterType((*BoolReply)(nil), "ddz.BoolReply")
	proto.RegisterType((*TrustShipRequest)(nil), "ddz.TrustShipRequest")
	proto.RegisterType((*RobotRequest)(nil), "ddz.RobotRequest")
	proto.RegisterType((*CardStyle)(nil), "ddz.CardStyle")
	proto.RegisterType((*PlayReply)(nil), "ddz.PlayReply")
	proto.RegisterType((*GameTableElement)(nil), "ddz.GameTableElement")
	proto.RegisterType((*GameTableReply)(nil), "ddz.GameTableReply")
	proto.RegisterType((*DealCardRequest)(nil), "ddz.DealCardRequest")
	proto.RegisterType((*DealCardReply)(nil), "ddz.DealCardReply")
}

func init() { proto.RegisterFile("ddz.proto", fileDescriptor_329728c9c8fc6b4b) }

var fileDescriptor_329728c9c8fc6b4b = []byte{
	// 641 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x55, 0x4b, 0x4f, 0xdb, 0x40,
	0x10, 0xc6, 0x79, 0x39, 0x19, 0x92, 0xe0, 0x6e, 0x69, 0x1b, 0x71, 0x42, 0xa6, 0x0f, 0x4a, 0x25,
	0x1e, 0xae, 0x7a, 0xea, 0x29, 0xc5, 0x2e, 0x44, 0x22, 0x0d, 0xdd, 0x58, 0x95, 0xe8, 0x05, 0x2d,
	0x78, 0x2b, 0x2c, 0xad, 0x63, 0xd7, 0x36, 0x08, 0xf3, 0x47, 0x7a, 0xef, 0x0f, 0xe8, 0x6f, 0xac,
	0xf6, 0x65, 0x87, 0x10, 0xa4, 0xde, 0x7b, 0xfc, 0x66, 0xbe, 0xfd, 0x3c, 0xfb, 0xed, 0xcc, 0x18,
	0x3a, 0x41, 0x70, 0xb7, 0x9b, 0xa4, 0x71, 0x1e, 0xa3, 0x7a, 0x10, 0xdc, 0xd9, 0x5b, 0xd0, 0xf9,
	0x14, 0xc7, 0x0c, 0xd3, 0x84, 0x15, 0xe8, 0x39, 0xb4, 0x52, 0x9a, 0x5d, 0xb3, 0x7c, 0x60, 0x6c,
	0x1a, 0xdb, 0x6d, 0xac, 0x90, 0xfd, 0xc7, 0x00, 0xcb, 0x4f, 0xaf, 0xb3, 0x7c, 0x7a, 0x15, 0x26,
	0x98, 0xfe, 0xbc, 0xa6, 0x59, 0x8e, 0xde, 0xc0, 0x5a, 0xc2, 0x48, 0x41, 0xd3, 0xf3, 0x30, 0xa0,
	0xb3, 0x3c, 0xcc, 0x0b, 0x71, 0xaa, 0x89, 0xfb, 0x32, 0x3c, 0x52, 0xd1, 0x39, 0xe2, 0x15, 0x99,
	0x05, 0x97, 0x24, 0x0d, 0x06, 0xb5, 0x4d, 0x63, 0xbb, 0xab, 0x89, 0xc7, 0x2a, 0x8a, 0xb6, 0xa0,
	0xc7, 0x48, 0x96, 0x57, 0x7a, 0x75, 0xa1, 0xd7, 0xe5, 0xc1, 0x52, 0x4d, 0x93, 0xf8, 0x59, 0xa1,
	0xd5, 0x10, 0x5a, 0x82, 0x74, 0xaa, 0x62, 0xf6, 0xef, 0x1a, 0x74, 0x71, 0x7c, 0x11, 0xe7, 0xba,
	0xd8, 0xd7, 0xa0, 0x3e, 0xb6, 0xbc, 0xd6, 0x70, 0x5e, 0x3d, 0x4e, 0x83, 0xc5, 0x4a, 0xbb, 0x3c,
	0x58, 0xd6, 0xf9, 0x16, 0xac, 0x1f, 0x24, 0x8d, 0x68, 0x7a, 0x50, 0xf1, 0xea, 0x82, 0xb7, 0xa6,
	0xe2, 0x0f, 0xa9, 0x4e, 0x45, 0x6d, 0xcc, 0x53, 0x9d, 0xc7, 0x6f, 0xdf, 0xfc, 0x97, 0xdb, 0xb7,
	0x1e, 0xde, 0x1e, 0xbd, 0x82, 0xbe, 0x20, 0x71, 0x90, 0xe5, 0x05, 0xa3, 0x03, 0x53, 0x48, 0x89,
	0xa3, 0x87, 0x3a, 0x68, 0x87, 0xd0, 0xe1, 0x60, 0xca, 0x01, 0x5a, 0x87, 0xa6, 0xa4, 0x4a, 0x5f,
	0x24, 0x40, 0x2f, 0xc0, 0x8c, 0xc2, 0xd9, 0xf9, 0x0d, 0x61, 0xc2, 0x88, 0x26, 0x6e, 0x45, 0xe1,
	0xec, 0x1b, 0x61, 0x22, 0x41, 0x6e, 0x45, 0xa2, 0xae, 0x12, 0xe4, 0x96, 0x27, 0xd6, 0xa1, 0x49,
	0x6f, 0xf3, 0x94, 0xa8, 0x5b, 0x4a, 0x60, 0x8f, 0xa1, 0xc3, 0xab, 0x93, 0x5d, 0xb6, 0x01, 0xed,
	0xd2, 0x0b, 0x43, 0xb0, 0x4a, 0x8c, 0x5e, 0xea, 0x32, 0xf8, 0xe7, 0x56, 0x9d, 0xfe, 0x2e, 0x6f,
	0xd7, 0xb2, 0x4a, 0x55, 0x96, 0xfd, 0xab, 0x06, 0xd6, 0x11, 0x89, 0xa8, 0x4f, 0x2e, 0x18, 0xf5,
	0x18, 0x8d, 0xe8, 0xec, 0x3f, 0x7b, 0xe2, 0x6a, 0x52, 0x4d, 0x91, 0xd5, 0x93, 0x3a, 0x84, 0x7e,
	0x69, 0x8c, 0x74, 0x7b, 0x0f, 0x4c, 0x2a, 0x1d, 0x1a, 0x18, 0x9b, 0xf5, 0xed, 0x55, 0xe7, 0x99,
	0xf0, 0x74, 0xd1, 0x3e, 0xac, 0x59, 0xf6, 0x57, 0x58, 0x73, 0x29, 0x61, 0xdc, 0xf4, 0x6a, 0x7a,
	0x1a, 0x79, 0x91, 0xc8, 0xde, 0xe8, 0x3b, 0x48, 0x08, 0xb8, 0xde, 0xf0, 0xe4, 0x70, 0x88, 0xdd,
	0x73, 0xff, 0xec, 0xd4, 0xc3, 0x22, 0xcf, 0xab, 0x4a, 0x48, 0x4a, 0xa2, 0x4c, 0x79, 0xaa, 0x90,
	0x9d, 0x41, 0xaf, 0x92, 0xe4, 0x45, 0x0d, 0xc0, 0x94, 0xaf, 0xb2, 0xaf, 0x3a, 0x40, 0xc3, 0x2a,
	0x73, 0xa0, 0x34, 0x34, 0xac, 0x32, 0x8e, 0x7a, 0x09, 0x0d, 0x97, 0xf7, 0xdc, 0xce, 0x2e, 0xb4,
	0x47, 0xae, 0xf7, 0xc5, 0x1f, 0xf9, 0x67, 0xa8, 0x0d, 0x8d, 0x93, 0x09, 0x76, 0xad, 0x15, 0xb4,
	0x0a, 0xe6, 0xe7, 0x21, 0x1e, 0x7b, 0xf8, 0xc0, 0x32, 0x2a, 0xe0, 0x58, 0xb5, 0x9d, 0x1d, 0xe8,
	0xdd, 0xbb, 0x13, 0xea, 0x41, 0x67, 0x72, 0xea, 0x8f, 0xc6, 0xa3, 0xef, 0x1e, 0x3f, 0x09, 0xd0,
	0x9a, 0x8e, 0x27, 0x13, 0xff, 0xd8, 0x32, 0x9c, 0xe3, 0xca, 0xa3, 0x29, 0x4d, 0x6f, 0xc2, 0x4b,
	0x8a, 0x3e, 0x80, 0x79, 0x44, 0xc5, 0x74, 0xa1, 0x75, 0x69, 0xd0, 0x7d, 0x13, 0x37, 0xd0, 0x42,
	0x34, 0x61, 0x85, 0xbd, 0xe2, 0x1c, 0xaa, 0xcd, 0x9a, 0x5d, 0x85, 0x89, 0x96, 0xda, 0x83, 0x06,
	0x5f, 0xb4, 0x48, 0xbe, 0xd4, 0xe2, 0xe2, 0xdd, 0x90, 0x43, 0x51, 0xce, 0x93, 0xbd, 0xe2, 0x7c,
	0x54, 0xdb, 0x4e, 0x0b, 0xbc, 0x83, 0x06, 0x4f, 0xa3, 0x27, 0x82, 0x39, 0xbf, 0x08, 0x97, 0x1c,
	0x76, 0xe7, 0x66, 0x49, 0x0b, 0xec, 0x3f, 0x2e, 0xf0, 0xf4, 0x7e, 0xfb, 0x28, 0x95, 0x8b, 0x96,
	0xf8, 0xa7, 0xbc, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x73, 0x37, 0x5f, 0xdf, 0x60, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DealCardServiceClient is the client API for DealCardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DealCardServiceClient interface {
	GetCard(ctx context.Context, in *DealCardRequest, opts ...grpc.CallOption) (*DealCardReply, error)
}

type dealCardServiceClient struct {
	cc *grpc.ClientConn
}

func NewDealCardServiceClient(cc *grpc.ClientConn) DealCardServiceClient {
	return &dealCardServiceClient{cc}
}

func (c *dealCardServiceClient) GetCard(ctx context.Context, in *DealCardRequest, opts ...grpc.CallOption) (*DealCardReply, error) {
	out := new(DealCardReply)
	err := c.cc.Invoke(ctx, "/ddz.DealCardService/GetCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DealCardServiceServer is the server API for DealCardService service.
type DealCardServiceServer interface {
	GetCard(context.Context, *DealCardRequest) (*DealCardReply, error)
}

// UnimplementedDealCardServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDealCardServiceServer struct {
}

func (*UnimplementedDealCardServiceServer) GetCard(ctx context.Context, req *DealCardRequest) (*DealCardReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCard not implemented")
}

func RegisterDealCardServiceServer(s *grpc.Server, srv DealCardServiceServer) {
	s.RegisterService(&_DealCardService_serviceDesc, srv)
}

func _DealCardService_GetCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DealCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DealCardServiceServer).GetCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ddz.DealCardService/GetCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DealCardServiceServer).GetCard(ctx, req.(*DealCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DealCardService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ddz.DealCardService",
	HandlerType: (*DealCardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCard",
			Handler:    _DealCardService_GetCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ddz.proto",
}

// TrustshipServiceClient is the client API for TrustshipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrustshipServiceClient interface {
	Ship(ctx context.Context, in *TrustShipRequest, opts ...grpc.CallOption) (*PlayReply, error)
}

type trustshipServiceClient struct {
	cc *grpc.ClientConn
}

func NewTrustshipServiceClient(cc *grpc.ClientConn) TrustshipServiceClient {
	return &trustshipServiceClient{cc}
}

func (c *trustshipServiceClient) Ship(ctx context.Context, in *TrustShipRequest, opts ...grpc.CallOption) (*PlayReply, error) {
	out := new(PlayReply)
	err := c.cc.Invoke(ctx, "/ddz.TrustshipService/Ship", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrustshipServiceServer is the server API for TrustshipService service.
type TrustshipServiceServer interface {
	Ship(context.Context, *TrustShipRequest) (*PlayReply, error)
}

// UnimplementedTrustshipServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTrustshipServiceServer struct {
}

func (*UnimplementedTrustshipServiceServer) Ship(ctx context.Context, req *TrustShipRequest) (*PlayReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ship not implemented")
}

func RegisterTrustshipServiceServer(s *grpc.Server, srv TrustshipServiceServer) {
	s.RegisterService(&_TrustshipService_serviceDesc, srv)
}

func _TrustshipService_Ship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrustShipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustshipServiceServer).Ship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ddz.TrustshipService/Ship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustshipServiceServer).Ship(ctx, req.(*TrustShipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TrustshipService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ddz.TrustshipService",
	HandlerType: (*TrustshipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ship",
			Handler:    _TrustshipService_Ship_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ddz.proto",
}

// RobotServiceClient is the client API for RobotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RobotServiceClient interface {
	Play(ctx context.Context, in *RobotRequest, opts ...grpc.CallOption) (*PlayReply, error)
}

type robotServiceClient struct {
	cc *grpc.ClientConn
}

func NewRobotServiceClient(cc *grpc.ClientConn) RobotServiceClient {
	return &robotServiceClient{cc}
}

func (c *robotServiceClient) Play(ctx context.Context, in *RobotRequest, opts ...grpc.CallOption) (*PlayReply, error) {
	out := new(PlayReply)
	err := c.cc.Invoke(ctx, "/ddz.RobotService/Play", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RobotServiceServer is the server API for RobotService service.
type RobotServiceServer interface {
	Play(context.Context, *RobotRequest) (*PlayReply, error)
}

// UnimplementedRobotServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRobotServiceServer struct {
}

func (*UnimplementedRobotServiceServer) Play(ctx context.Context, req *RobotRequest) (*PlayReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Play not implemented")
}

func RegisterRobotServiceServer(s *grpc.Server, srv RobotServiceServer) {
	s.RegisterService(&_RobotService_serviceDesc, srv)
}

func _RobotService_Play_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotServiceServer).Play(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ddz.RobotService/Play",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotServiceServer).Play(ctx, req.(*RobotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RobotService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ddz.RobotService",
	HandlerType: (*RobotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Play",
			Handler:    _RobotService_Play_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ddz.proto",
}

// GameTableServiceClient is the client API for GameTableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameTableServiceClient interface {
	Play(ctx context.Context, in *RobotRequest, opts ...grpc.CallOption) (*GameTableReply, error)
}

type gameTableServiceClient struct {
	cc *grpc.ClientConn
}

func NewGameTableServiceClient(cc *grpc.ClientConn) GameTableServiceClient {
	return &gameTableServiceClient{cc}
}

func (c *gameTableServiceClient) Play(ctx context.Context, in *RobotRequest, opts ...grpc.CallOption) (*GameTableReply, error) {
	out := new(GameTableReply)
	err := c.cc.Invoke(ctx, "/ddz.GameTableService/Play", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameTableServiceServer is the server API for GameTableService service.
type GameTableServiceServer interface {
	Play(context.Context, *RobotRequest) (*GameTableReply, error)
}

// UnimplementedGameTableServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGameTableServiceServer struct {
}

func (*UnimplementedGameTableServiceServer) Play(ctx context.Context, req *RobotRequest) (*GameTableReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Play not implemented")
}

func RegisterGameTableServiceServer(s *grpc.Server, srv GameTableServiceServer) {
	s.RegisterService(&_GameTableService_serviceDesc, srv)
}

func _GameTableService_Play_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameTableServiceServer).Play(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ddz.GameTableService/Play",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameTableServiceServer).Play(ctx, req.(*RobotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameTableService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ddz.GameTableService",
	HandlerType: (*GameTableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Play",
			Handler:    _GameTableService_Play_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ddz.proto",
}
